# Generated by Django 6.0 on 2026-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='has_projector',
        ),
        migrations.AddField(
            model_name='venue',
            name='equipment',
            field=models.CharField(blank=True, help_text='e.g. Projector, Wifi, AC', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
