# Generated by Django 6.0 on 2026-01-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_venue_has_ac_remove_venue_has_projector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='booking_docs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('STUDY', 'Study'), ('EVENT', 'Event')], default='STUDY', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
