# Generated by Django 6.0 on 2026-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking_document_booking_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addon_equipment',
            field=models.TextField(blank=True, help_text='List any extra equipment needed (e.g., Extra Mic, Extension Cord).', null=True),
        ),
    ]
