# Generated by Django 6.0 on 2026-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_booking_options_alter_venue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_hour', models.IntegerField(default=8, help_text='Opening hour (0-23)')),
                ('close_hour', models.IntegerField(default=20, help_text='Closing hour (0-23)')),
                ('slot_duration_minutes', models.IntegerField(default=60, help_text='Duration of each time slot in minutes')),
                ('days_in_advance', models.IntegerField(default=30, help_text='Maximum days in advance for bookings')),
            ],
            options={
                'verbose_name_plural': 'Venue Schedule',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(blank=True, help_text='Selected time slot (e.g. 09:00-10:00)', max_length=20, null=True),
        ),
    ]
